better error logging when is a script isn't executable

diff --git a/ns b/ns
--- a/ns
+++ b/ns
@@ -54,7 +54,13 @@ fi
 if [[ "run" == "$subcommand" || "run-piped" == "$subcommand" || "source-piped" == "$subcommand" ]]; then
     script=$(NS_PATH="$NS_PATH" ns_which +x "$1")
     leading=". ns import "
-    import_lines=$(grep "^${leading}" "$script" | sed "s/^${leading}//")
+    import_lines=
+    if [[ -n "$script" ]]; then
+        import_lines=$(grep "^${leading}" "$script" | sed "s/^${leading}//")
+    else
+        echo "ns attempted to find an executable script, but 'ns_which ${1}' failed to locate it" 1>&2
+        false
+    fi
     # echo "test imp lines ${import_lines}<EOL>" >&2
     NS_AUTO_LINES="$import_lines" . ns_auto_export_lines
     # exps=$(grep "$leading" "$script" | head -1)
@@ -78,7 +84,12 @@ if [[ "run" == "$subcommand" || "run-piped" == "$subcommand" || "source-piped" =
         pipe_chain=$(NS_PATH="$NS_PATH" ARGS="${save_args}" ns_args_to_pipes)
         eval "$pipe_chain"
     else
-        "$script"
+        if [[ ! -x "$script" ]]; then
+            echo "ns run attempted for script (${script}) but does not have an execute permission" 1>&2
+            false
+        else
+           "$script" # || (echo "${script} failed ${save_args}" 1>>&2 2>>/dev/null)
+        fi
     fi
     ec=$?
 
@@ -91,7 +102,13 @@ if [[ "run" == "$subcommand" || "run-piped" == "$subcommand" || "source-piped" =
     #      Really, what is intended is to just delete the ones that don't get
     #      re-exported.
     leading=". ns export "
-    export_lines=$(grep "^${leading}" "$script" | sed "s/^${leading}//")
+    export_lines=
+    if [[ -n "$script" ]]; then
+        export_lines=$(grep "^${leading}" "$script" | sed "s/^${leading}//")
+    else
+        echo "ns could not find exports for script (${script})" 1>&2
+        false
+    fi
     del_lines=$(NS_LHS="$import_lines" NS_RHS="$export_lines" ns_arg_minus)  # (lhs - rhs)
     # delete must happen in reversed line order, otherwise resolving a parameter
     # expression will fail (and instead it tries to delete an empty variable)
